### ISSUE TITLE
Bug ndk create album akun wo baru

### ISSUE THREAD

**Issue by yusuf12344** [DevT-Brain-Corp/Nikahkuy#25]
Pas gawe album  ndk akun wo baru, album e masuk ndk wo sg pesona beauty

**Comment by yusuf12344** [comment]
pas masuk akun guest, wo sg baru daftar sek error

**Comment by yusuf12344** [comment]
[](url)
![Screenshot (45)](https://user-images.githubusercontent.com/37580989/84472450-5f859400-acb1-11ea-8bab-a590fbdeb90e.png)

**Comment by fahmifayyadh** [comment]
waktu album kosong tetap error dan masalah pada create album ya?

**Comment by yusuf12344** [comment]
yupp

**Comment by fahmifayyadh** [comment]
Bug fixed : silahkan cek branch master
